### ISSUE TITLE
cdk package on linux not callable

### ISSUE THREAD

**Issue by thomasly** [hcji/PyFingerprint#4]
I am trying to use this package to calculate PubChem fingerprint. I have installed java runtime and pype1 but still got the Error below. I don't have issue when running the script on Windows.

TypeError: Package <Java package org.openscience.cdk.fingerprint.Fingerprinter._name> is not Callable

The full Error message is:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/slgnn/slgnn/training/train_gcn.py", line 199, in <module>
    "data/ZINC/zinc_ghose_10000.hdf5")
  File "/workspace/slgnn/slgnn/models/gcn/utils.py", line 75, in load_encoder_data
    sm, fp_type='pubchem', output="vector") for sm in smiles]
  File "/workspace/slgnn/slgnn/models/gcn/utils.py", line 75, in <listcomp>
    sm, fp_type='pubchem', output="vector") for sm in smiles]
  File "/opt/conda/lib/python3.6/site-packages/PyFingerprint/All_Fingerprint.py", line 23, in get_fingerprint
    res = cdk_fingerprint(smi, fp_type, nbit, depth, output)
  File "/opt/conda/lib/python3.6/site-packages/PyFingerprint/CDK_Fingerprint.py", line 40, in cdk_fingerprint
    _fingerprinters = {"daylight":cdk.fingerprint.Fingerprinter(size, depth)
  File "/opt/conda/lib/python3.6/site-packages/jpype/_jpackage.py", line 124, in __call__
    raise TypeError("Package {0} is not Callable".format(self._name))
TypeError: Package <Java package org.openscience.cdk.fingerprint.Fingerprinter._name> is not Callable

**Comment by hcji** [comment]
The error may caused by the cdk path:
`cdk_path = PyFingerprint.__path__[0] + '\\CDK\\cdk-2.2.jar' `

It has been changed to:
`cdk_path = os.path.join(PyFingerprint.__path__[0] + 'CDK', 'cdk-2.2.jar')`
which may make sense. Without a linux PC, not test yet.

**Comment by thomasly** [comment]
Thank you for your reply. The change works. I tested on my Linux system.
